AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: API Test

Globals:
  Function:
    Timeout: 5
    Runtime: python3.9
    Handler: lambda_function.lambda_handler

Resources:
  MiApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: true

  LambdaGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get/
      Policies: AmazonDynamoDBFullAccess
      Events:
        Get:
          Type: HttpApi
          Properties:
            Path: /items
            Method: get
            ApiId: !Ref MiApi
  LambdaPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: post/
      Policies: AmazonDynamoDBFullAccess
      Events:
        Get:
          Type: HttpApi
          Properties:
            Path: /items
            Method: post
            ApiId: !Ref MiApi
  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: "email"
        Type: "String"
      TableName: "tabledata"

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${MiApi}.execute-api.${AWS::Region}.amazonaws.com"
